// fine you dont wana import ill just paste it here
// import Shop from "../assets/shop.json";
export const Shop = [
  {
    id: "item_pile_of_stickers_10",
    name: "Pile of Stickers",
    subtitle: "3, and random...",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/pile_of_stickers.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 17,
    priceGlobal: 17,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 0.7333333333333334,
    maximumHoursEstimated: 3.666666666666667,
  },
  {
    id: "item_openai_credits_14",
    name: "OpenAI credits",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/card_grant_openai.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 28,
    priceGlobal: 28,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.1666666666666665,
    maximumHoursEstimated: 5.833333333333332,
  },
  {
    id: "item_hetzner_credits_29",
    name: "Hetzner credits",
    subtitle: "buy more than one!<br/>get hosting for a while!",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/card_grant_hetzner.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 28,
    priceGlobal: 28,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.1666666666666665,
    maximumHoursEstimated: 5.833333333333332,
  },
  {
    id: "item_anthropic_credits",
    name: "Anthropic Credits",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/card_grant_anthropic.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 28,
    priceGlobal: 28,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.1666666666666665,
    maximumHoursEstimated: 5.833333333333332,
  },
  {
    id: "item_heroku_credits_50",
    name: "Heroku Credits",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/card_grant_heroku.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 28,
    priceGlobal: 28,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.1666666666666665,
    maximumHoursEstimated: 5.833333333333332,
  },
  {
    id: "item_hack_club_microsd_card_28",
    name: "Hack Club MicroSD card",
    subtitle: "might hold 64gb worth of data!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/microsd.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 30,
    priceGlobal: 32,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.1666666666666665,
    maximumHoursEstimated: 5.833333333333332,
  },
  {
    id: "item_logic_analyzer_17",
    name: "Logic Analyzer",
    subtitle: "omgwtfbbq! fx2lafw ftw!!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/logic_analyzer.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 34,
    priceGlobal: 34,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.4999999999999998,
    maximumHoursEstimated: 7.499999999999998,
  },
  {
    id: "item_mcmaster_credits_51",
    name: "McMaster-Carr Credits",
    subtitle: "buy yourself something pretty...",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/card_grant_mcmaster.png",
    enabledUs: true,
    enabledEu: false,
    enabledIn: false,
    enabledXx: false,
    enabledCa: false,
    enabledAll: true,
    priceUs: 38,
    priceGlobal: 38,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.5,
    maximumHoursEstimated: 7.499999999999999,
  },
  {
    id: "item_ifixit_credits_52",
    name: "iFixit Credits",
    subtitle: "parts? tools? sure!",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/card_grant_ifixit.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 38,
    priceGlobal: 38,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.5499999999999998,
    maximumHoursEstimated: 7.749999999999999,
  },
  {
    id: "item_bite_size_linux_6",
    name: "Bite Size Linux",
    subtitle: " by Julia Evans",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/bite_size_linux.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 40,
    priceGlobal: 40,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.4999999999999998,
    maximumHoursEstimated: 7.499999999999998,
  },
  {
    id: "item_bite_size_bash_7",
    name: "Bite Size Bash",
    subtitle: " by Julia Evans",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/bite_size_bash.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 40,
    priceGlobal: 40,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.4999999999999998,
    maximumHoursEstimated: 7.499999999999998,
  },
  {
    id: "item_how_dns_works_8",
    name: "How DNS Works",
    subtitle: " by Julia Evans",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/how_dns_works.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 40,
    priceGlobal: 40,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.4999999999999998,
    maximumHoursEstimated: 7.499999999999998,
  },
  {
    id: "item_domain__1_year__11",
    name: "Domain (1 year)",
    subtitle: "(anything under $10!)",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/domain.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 40,
    priceGlobal: 40,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.6666666666666665,
    maximumHoursEstimated: 8.333333333333332,
  },
  {
    id: "item_how_git_works_42",
    name: "How Git Works",
    subtitle: "by Julia Evans",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/how_git_works.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: false,
    enabledAll: false,
    priceUs: 40,
    priceGlobal: 40,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.7499999999999996,
    maximumHoursEstimated: 8.749999999999996,
  },
  {
    id: "item_hell_yes_css__43",
    name: "Hell Yes! CSS!",
    subtitle: "by Julia Evans",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/hell_yes_css.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: false,
    enabledAll: false,
    priceUs: 40,
    priceGlobal: 40,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.7499999999999996,
    maximumHoursEstimated: 8.749999999999996,
  },
  {
    id: "item_signed_photo_of_malted_19",
    name: "Signed photo of Malted",
    subtitle: "(may incur customs charges)",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/signed_photo_of_malted.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 42,
    priceGlobal: 42,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.7266666666666666,
    maximumHoursEstimated: 8.633333333333331,
  },
  {
    id: "item_the_pocket_guide_to_debugging_44",
    name: "The Pocket Guide to Debugging",
    subtitle: "by Julia Evans",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/pocket_guide_to_debugging.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: false,
    priceUs: 50,
    priceGlobal: 50,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 2.0999999999999996,
    maximumHoursEstimated: 10.499999999999998,
  },
  {
    id: "item_digital_calipers_50",
    name: "Digital Calipers",
    subtitle: "plastic, but fantastic!",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/cheap_digital_calipers.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 50,
    priceGlobal: 50,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 1.9833333333333332,
    maximumHoursEstimated: 9.916666666666666,
  },
  {
    id: "item_pcb_56",
    name: "PCB manufacturing credit!",
    subtitle:
      'works <a href="https://github.com/hackclub/OnBoard/blob/main/docs/VENDORS.md" target="_blank"><u>anywhere OnBoard does</u></a>!',
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/card_grant_pcb.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 55,
    priceGlobal: 55,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 2.333333333333333,
    maximumHoursEstimated: 11.666666666666664,
  },
  {
    id: "item_itsy_bitsy_1",
    name: "Adafruit ItsyBitsy M4 Express",
    subtitle: "ARMed and dangerous!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/itsy_bitsy_m4.png",
    enabledUs: true,
    enabledEu: false,
    enabledIn: false,
    enabledXx: false,
    enabledCa: false,
    enabledAll: true,
    priceUs: 55,
    priceGlobal: 55,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 2.1666666666666665,
    maximumHoursEstimated: 10.833333333333332,
  },
  {
    id: "item_hot_glue_gun",
    name: "Hot Glue Gun",
    subtitle: "affix some things to some stuff!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/glue_gun.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 57,
    priceGlobal: 57,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 2.333333333333333,
    maximumHoursEstimated: 11.666666666666664,
  },
  {
    id: "item_parts_credit",
    name: "DigiKey/LCSC Credit",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/card_grant_parts.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 63,
    priceGlobal: 63,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 3.333333333333333,
    maximumHoursEstimated: 16.666666666666664,
  },
  {
    id: "item_raspberry_pi_13_us",
    name: "Raspberry Pi",
    subtitle: "kit with Zero 2 W!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/raspberry_pi.png",
    enabledUs: true,
    enabledEu: false,
    enabledIn: false,
    enabledXx: false,
    enabledCa: false,
    enabledAll: false,
    priceUs: 73,
    priceGlobal: 73,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 3.173333333333334,
    maximumHoursEstimated: 15.866666666666667,
  },
  {
    id: "item_raspberry_pi_13_intl",
    name: "Raspberry Pi",
    subtitle: "kit with Zero 2 W!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/raspberry_pi.png",
    enabledUs: false,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 73,
    priceGlobal: 73,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 3.4,
    maximumHoursEstimated: 17,
  },
  {
    id: "item_github_invertocat_pin__39",
    name: "GitHub Invertocat Pin!",
    subtitle: "stylish!!!",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/gh_invertocat_pin.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 76,
    priceGlobal: 76,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 3.0333333333333337,
    maximumHoursEstimated: 15.166666666666666,
  },
  {
    id: "item_signed_photo_of_graham_darcey_16",
    name: "Signed photo of Graham Darcey",
    subtitle: "(rare!!!)",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/signed_photo_of_graham.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 80,
    priceGlobal: 80,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 3.6999999999999993,
    maximumHoursEstimated: 18.499999999999996,
  },
  {
    id: "item_pinecil_20",
    name: "Pinecil",
    subtitle: "64 whole pines!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/pinecil.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 82,
    priceGlobal: 82,
    fulfilledAtEnd: true,
    comingSoon: true,
    outOfStock: true,
    minimumHoursEstimated: 3.333333333333333,
    maximumHoursEstimated: 16.666666666666664,
  },
  {
    id: "item_cube",
    name: "c u b e",
    subtitle: "XMD XT3 V1!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/cube.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 110,
    priceGlobal: 110,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 4.374999999999999,
    maximumHoursEstimated: 21.874999999999996,
  },
  {
    id: "item_github_notebook_37",
    name: "GitHub Notebook",
    subtitle: "Denik Layflat!",
    imageUrl:
      "https://noras-secret-cdn.hackclub.dev/shop/gh_denik_layflat_notebook.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 120,
    priceGlobal: 140,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 4.999999999999999,
    maximumHoursEstimated: 24.999999999999996,
  },
  {
    id: "item_blah_j_5",
    name: "Blåhaj",
    subtitle: "⚠️warning: smolhaj!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/blahaj.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 123,
    priceGlobal: 123,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 4.966666666666666,
    maximumHoursEstimated: 24.83333333333333,
  },
  {
    id: "item_ham_radio",
    name: "Baofeng UV-5R",
    subtitle: "ham! but no cheese...",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/baofeng.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: false,
    enabledCa: false,
    enabledAll: true,
    priceUs: 126,
    priceGlobal: 126,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 5.224999999999999,
    maximumHoursEstimated: 26.124999999999993,
  },
  {
    id: "item_lockpick_set_31",
    name: "Lockpick set",
    subtitle:
      '<a href="https://toool.us" target="_blank"><u>TOOOL</u></a>\'s Necessary Nine!',
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/lockpicks.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 151,
    priceGlobal: 154,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 6.3,
    maximumHoursEstimated: 31.499999999999996,
  },
  {
    id: "item_github_keycaps_38",
    name: "GitHub Keycaps",
    subtitle: "assorted pack of 8!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/gh_keycaps.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 154,
    priceGlobal: 154,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 6.411666666666666,
    maximumHoursEstimated: 32.05833333333333,
  },
  {
    id: "item_hack_club_socks__34",
    name: "Hack Club socks!",
    subtitle: "(genuinely really comfy!)",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/hc_socks.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 156,
    priceGlobal: 156,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 6.5,
    maximumHoursEstimated: 32.49999999999999,
  },
  {
    id: "item_factorio",
    name: "Factorio",
    subtitle: "a great use of your time!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/factorio.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 170,
    priceGlobal: 170,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 6.766666666666665,
    maximumHoursEstimated: 33.83333333333332,
  },
  {
    id: "item_badger",
    name: "GitHub Universe Badge",
    subtitle:
      '<a href="https://gh.io/badger" target="_blank"><u>wait</u></a>, this is just an RP2350 and an e-ink display...',
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/gh_badger.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 172,
    priceGlobal: 172,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 7.083333333333332,
    maximumHoursEstimated: 35.41666666666666,
  },
  {
    id: "item_fudge",
    name: "1 lb fudge from place next to HQ",
    subtitle: "even the dinosaur likes it!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/fudge.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 220,
    priceGlobal: 240,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 10.833333333333332,
    maximumHoursEstimated: 54.16666666666666,
  },
  {
    id: "item_yubikey_9",
    name: "YubiKey",
    subtitle: "5C NFC, GitHub-branded",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/yubikey.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 264,
    priceGlobal: 264,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 10.999999999999998,
    maximumHoursEstimated: 54.999999999999986,
  },
  {
    id: "item_dremel_4300_kit_33",
    name: "Dremel 4300 kit",
    subtitle: "5 attachments and 40 accessories!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/dremel.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 265,
    priceGlobal: 265,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 10.999999999999998,
    maximumHoursEstimated: 54.999999999999986,
  },
  {
    id: "item_raspberry_pi_5_45",
    name: "Raspberry Pi 5",
    subtitle: "4GB RAM & 64GB µSD!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/raspberry_pi_5.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 265,
    priceGlobal: 275,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 10.799999999999999,
    maximumHoursEstimated: 53.99999999999999,
  },
  {
    id: "item_logitech_mx_master_3s",
    name: "Logitech MX Master 3S",
    subtitle: "Wireless, quiet and fast! Doesn't need cheese.",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/mx_master.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 480,
    priceGlobal: 480,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 18.999999999999996,
    maximumHoursEstimated: 94.99999999999997,
  },
  {
    id: "item_blot",
    name: "Blot",
    subtitle:
      'let\'s just call it a <a href="https://blot.hackclub.com" target="_blank"><u>draw</u></a>',
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/blot.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 675,
    priceGlobal: 675,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 26.666666666666664,
    maximumHoursEstimated: 133.33333333333331,
  },
  {
    id: "item_github_miir_backpack_35",
    name: "GitHub MiiR® Backpack",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/gh_miir_backpack.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 725,
    priceGlobal: 725,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 31.599999999999998,
    maximumHoursEstimated: 157.99999999999997,
  },
  {
    id: "item_system76_launch_keyboard_48",
    name: "System76 Launch Keyboard",
    subtitle:
      '<a href="https://github.com/system76/launch" target="_blank"><u>open-source!!!</u></a>',
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/s76_launch.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 790,
    priceGlobal: 790,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 31.349999999999994,
    maximumHoursEstimated: 156.74999999999997,
  },
  {
    id: "item_flipper_32",
    name: "Flipper",
    subtitle: "(zero!)",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/flipper.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 850,
    priceGlobal: 850,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 35.416666666666664,
    maximumHoursEstimated: 177.08333333333331,
  },
  {
    id: "item_bambu_lab_a1_mini_49",
    name: "Bambu Lab A1 Mini",
    subtitle: "print print print print print!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/bambu_a1_mini.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 1000,
    priceGlobal: 1000,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 41.666666666666664,
    maximumHoursEstimated: 208.3333333333333,
  },
  {
    id: "item_thermal_camera",
    name: "Thermal imaging camera",
    subtitle: "hot stuff!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/thermal_cam.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 1015,
    priceGlobal: 1015,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 42.166666666666664,
    maximumHoursEstimated: 210.83333333333331,
  },
  {
    id: "item_hot_air",
    name: "Hot-air rework station",
    subtitle: "(Quick 861DW)",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/quick.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: false,
    enabledCa: false,
    enabledAll: true,
    priceUs: 1120,
    priceGlobal: 1120,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 46.666666666666664,
    maximumHoursEstimated: 233.3333333333333,
  },
  {
    id: "item_100mhz_oscilloscope_53",
    name: "100MHZ Oscilloscope",
    subtitle:
      'Siglent <a href="https://siglentna.com/wp-content/uploads/dlm_uploads/2021/04/SDS1000CMLplus_DataSheet_DS0101A-E03A.pdf" target="_blank"><u>SDS1102CML+</u></a>',
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/1152cml.png",
    enabledUs: true,
    enabledEu: false,
    enabledIn: false,
    enabledXx: false,
    enabledCa: false,
    enabledAll: true,
    priceUs: 1210,
    priceGlobal: 1210,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 50.24999999999999,
    maximumHoursEstimated: 251.24999999999994,
  },
  {
    id: "item_ipad_46",
    name: "iPad",
    subtitle: "10th gen (w/ Apple Pencil!)",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/ipad.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 2090,
    priceGlobal: 2090,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 77.49999999999999,
    maximumHoursEstimated: 387.49999999999994,
  },
  {
    id: "item_framework_laptop_13_factory_seconds_53",
    name: 'Framework Laptop 13"',
    subtitle: "(factory seconds)",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/fw_13.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 3075,
    priceGlobal: 3075,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 127.99999999999999,
    maximumHoursEstimated: 639.9999999999999,
  },
  {
    id: "item_macbook_air_54",
    name: 'MacBook Air M2 13"',
    subtitle: "refurbished, 8GB RAM",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/macbook_air_m2.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 4000,
    priceGlobal: 4000,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 166.66666666666666,
    maximumHoursEstimated: 833.3333333333331,
  },
  {
    id: "item_framework_laptop_16__52",
    name: 'Framework Laptop 16"',
    subtitle: "we only have one of these, grab it if you can!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/fw_16_inch.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: false,
    enabledXx: false,
    enabledCa: true,
    enabledAll: true,
    priceUs: 4980,
    priceGlobal: 4980,
    fulfilledAtEnd: true,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 207.49999999999997,
    maximumHoursEstimated: 1037.4999999999998,
  },
  {
    id: "item_defcon_ticket_55",
    name: "ticket to DEF CON",
    subtitle: "flight and hotel included!",
    imageUrl: "https://noras-secret-cdn.hackclub.dev/shop/defcon.png",
    enabledUs: true,
    enabledEu: true,
    enabledIn: true,
    enabledXx: true,
    enabledCa: true,
    enabledAll: true,
    priceUs: 6675,
    priceGlobal: 6675,
    fulfilledAtEnd: false,
    comingSoon: false,
    outOfStock: false,
    minimumHoursEstimated: 277.99999999999994,
    maximumHoursEstimated: 1389.9999999999995,
  },
];

// js typings & data retrival
export type Shop = ShopItem[];

export interface ShopItem {
  id: string;
  name: string;
  subtitle?: string;
  imageUrl: string;
  enabledUs: boolean;
  enabledEu: boolean;
  enabledIn: boolean;
  enabledXx: boolean;
  enabledCa: boolean;
  priceUs: number;
  priceGlobal: number;
  fulfilledAtEnd: boolean;
  comingSoon: boolean;
  outOfStock: boolean;
}

export function getShop(): Shop {
  return Shop;
}
export function getShopItem(id: string): ShopItem {
  return Shop.find((e) => e.id === id);
}

export function searchShop(query: string): ShopItem[] {
  return Shop.filter((e) => e.name.toLowerCase().includes(query.toLowerCase()));
  // return Shop.filter(e => e.name.toLowerCase().includes(query.toLowerCase()));
}
